services:
  db:
    image: mysql:8.0
    container_name: my_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3305:3306"
    restart : always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpassword"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    depends_on:
      db:
        condition: service_healthy   # WordPress chỉ start khi db healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
volumes:
  wordpress_data:
  mysql_data: